### ISSUE TITLE
Command line client

### ISSUE THREAD

**Issue by nichtich** [reconciliation-api/census#25]
I was surprised there is no simple command line client to query a reconciliation endpoint. Following the specification I started to write such client but it looks like the query format differs between specification and implementation. What am I doing wrong?:

    curl -X POST "https://wikidata.reconci.link/en/api" -H 'Content-Type: application/json' -d '{"queries":[{"query":"Marx","limit":"10"}]}'

**Comment by wetneb** [comment]
The syntax you use looks correct if for draft version of the specs, but the reconciliation service you are querying only supports the protocol version 0.1 and 0.2, which you can see by GETting its manifest https://wikidata.reconci.link/en/api.

**Comment by nichtich** [comment]
Oh, thanks, I'll adopt my client to support multiple versions! What service can I use to test the draft API? At https://reconciliation-api.github.io/testbench/#/ most services use 0.1 or 0.2 and https://fornpunkt.se/apis/reconciliation/geonames does not work neither.

**Comment by wetneb** [comment]
I'm not aware of any service that implements the current draft specification so far. It's a moving target, of course.

**Comment by fsteeg** [comment]
Client is listed in census: https://reconciliation-api.github.io/census/clients/, closing. 

Thank you for your contribution @nichtich!
