### ISSUE TITLE
AGDISTIS/ MAG as new service

### ISSUE THREAD

**Issue by vdanielupb** [reconciliation-api/census#3]
AGDISTIS/MAG should be added as service:
Project website: http://aksw.org/Projects/AGDISTIS.html
Source code: https://github.com/dice-group/AGDISTIS
Documentation: https://github.com/dice-group/AGDISTIS/wiki
API: (AGDISTIS): http://akswnc9.informatik.uni-leipzig.de:8113/AGDISTIS
API: (MAG): http://akswnc9.informatik.uni-leipzig.de:8113/AGDISTIS

**Comment by wetneb** [comment]
Hi @vdanielupb, thanks for this!

At the moment we only list services which support the current OpenRefine reconciliation API. It seems to me that this project does not implement that API. Moreover, there is also a difference between the tasks: the reconciliation api is about linking records across databases, whereas AGDISTIS/MAP annotates text with entities. These are different, but closely-related tasks.

One thing that could be worth discussing is whether the reconciliation API should also support text annotation like AGDISTIS/MAP does.

**Comment by wetneb** [comment]
Closing since this seems to have arisen from a misunderstanding of the scope of this community group.
